name: My First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: First Job Welcome Messege
          run: |
            echo "The First Job"
            echo "My first Messege" >> messege.txt

    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
      
        - name: Second Job file reading
          run: |
            echo "The Seond Job"
            ls -al