name: My First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: First Job Welcome Messege
          run: |
            echo "The First Job"

        - name: Dump github context
          run: echo '${{ toJson(github) }}'

